# Generated by Django 4.0 on 2022-08-29 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='desc10',
            field=models.TextField(default='empty', max_length=50000),
        ),
        migrations.AddField(
            model_name='list',
            name='desc2',
            field=models.TextField(default='empty', max_length=50000),
        ),
        migrations.AddField(
            model_name='list',
            name='desc3',
            field=models.TextField(default='empty', max_length=50000),
        ),
        migrations.AddField(
            model_name='list',
            name='desc4',
            field=models.TextField(default='empty', max_length=50000),
        ),
        migrations.AddField(
            model_name='list',
            name='desc5',
            field=models.TextField(default='empty', max_length=50000),
        ),
        migrations.AddField(
            model_name='list',
            name='desc6',
            field=models.TextField(default='empty', max_length=50000),
        ),
        migrations.AddField(
            model_name='list',
            name='desc7',
            field=models.TextField(default='empty', max_length=50000),
        ),
        migrations.AddField(
            model_name='list',
            name='desc8',
            field=models.TextField(default='empty', max_length=50000),
        ),
        migrations.AddField(
            model_name='list',
            name='desc9',
            field=models.TextField(default='empty', max_length=50000),
        ),
        migrations.AddField(
            model_name='list',
            name='tit10',
            field=models.CharField(default='empty', max_length=500),
        ),
        migrations.AddField(
            model_name='list',
            name='tit2',
            field=models.CharField(default='empty', max_length=500),
        ),
        migrations.AddField(
            model_name='list',
            name='tit3',
            field=models.CharField(default='empty', max_length=500),
        ),
        migrations.AddField(
            model_name='list',
            name='tit4',
            field=models.CharField(default='empty', max_length=500),
        ),
        migrations.AddField(
            model_name='list',
            name='tit5',
            field=models.CharField(default='empty', max_length=500),
        ),
        migrations.AddField(
            model_name='list',
            name='tit6',
            field=models.CharField(default='empty', max_length=500),
        ),
        migrations.AddField(
            model_name='list',
            name='tit7',
            field=models.CharField(default='empty', max_length=500),
        ),
        migrations.AddField(
            model_name='list',
            name='tit8',
            field=models.CharField(default='empty', max_length=500),
        ),
        migrations.AddField(
            model_name='list',
            name='tit9',
            field=models.CharField(default='empty', max_length=500),
        ),
        migrations.AlterField(
            model_name='list',
            name='desc',
            field=models.TextField(default='empty', max_length=50000),
        ),
        migrations.AlterField(
            model_name='list',
            name='tit',
            field=models.CharField(default='empty', max_length=500),
        ),
    ]
