# Generated by Django 4.0 on 2022-09-07 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_list_posted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='list',
            name='desc10',
        ),
        migrations.RemoveField(
            model_name='list',
            name='desc2',
        ),
        migrations.RemoveField(
            model_name='list',
            name='desc3',
        ),
        migrations.RemoveField(
            model_name='list',
            name='desc4',
        ),
        migrations.RemoveField(
            model_name='list',
            name='desc5',
        ),
        migrations.RemoveField(
            model_name='list',
            name='desc6',
        ),
        migrations.RemoveField(
            model_name='list',
            name='desc7',
        ),
        migrations.RemoveField(
            model_name='list',
            name='desc8',
        ),
        migrations.RemoveField(
            model_name='list',
            name='desc9',
        ),
        migrations.RemoveField(
            model_name='list',
            name='tit',
        ),
        migrations.RemoveField(
            model_name='list',
            name='tit10',
        ),
        migrations.RemoveField(
            model_name='list',
            name='tit2',
        ),
        migrations.RemoveField(
            model_name='list',
            name='tit3',
        ),
        migrations.RemoveField(
            model_name='list',
            name='tit4',
        ),
        migrations.RemoveField(
            model_name='list',
            name='tit5',
        ),
        migrations.RemoveField(
            model_name='list',
            name='tit6',
        ),
        migrations.RemoveField(
            model_name='list',
            name='tit7',
        ),
        migrations.RemoveField(
            model_name='list',
            name='tit8',
        ),
        migrations.RemoveField(
            model_name='list',
            name='tit9',
        ),
    ]
