# Generated by Django 4.0 on 2022-09-07 09:27

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_list_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='content',
            field=ckeditor.fields.RichTextField(default=' ', null=True),
        ),
    ]
