# Generated by Django 4.0 on 2022-09-14 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_bookgenre_musicgenre_musiclist_booklist'),
    ]

    operations = [
        migrations.AddField(
            model_name='booklist',
            name='type',
            field=models.CharField(default='book', max_length=10),
        ),
        migrations.AddField(
            model_name='list',
            name='type',
            field=models.CharField(default='Movie', max_length=10),
        ),
        migrations.AddField(
            model_name='musiclist',
            name='type',
            field=models.CharField(default='Music', max_length=10),
        ),
    ]
