# Generated by Django 4.0 on 2022-09-18 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_list_slug_musiclist_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('List', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='app.list')),
            ],
        ),
    ]
