# Generated by Django 4.0 on 2022-09-21 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_rename_list_comment_list_alter_comment_body'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
