# Generated by Django 4.0 on 2022-09-22 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_booklist_creator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booklist',
            name='creator',
        ),
    ]
