# Generated by Django 4.0 on 2022-10-08 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_profile_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='fav_Book_genre',
            field=models.ManyToManyField(to='app.BookGenre'),
        ),
        migrations.AddField(
            model_name='profile',
            name='fav_movie_genre',
            field=models.ManyToManyField(to='app.Genre'),
        ),
        migrations.AddField(
            model_name='profile',
            name='fav_music_genre',
            field=models.ManyToManyField(to='app.MusicGenre'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='', upload_to='profiles_pics'),
        ),
    ]
