# Generated by Django 4.0 on 2022-10-11 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_profile_fav_book_genre_profile_fav_movie_genre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookreview',
            name='type',
            field=models.TextField(default='book', max_length=10),
        ),
        migrations.AddField(
            model_name='musicreview',
            name='type',
            field=models.TextField(default='music', max_length=10),
        ),
        migrations.AddField(
            model_name='review',
            name='type',
            field=models.TextField(default='movie', max_length=10),
        ),
    ]
