# Generated by Django 4.0 on 2022-10-20 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_bookreview_type_musicreview_type_review_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booklist',
            name='title',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='list',
            name='title',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='musiclist',
            name='title',
            field=models.CharField(max_length=120),
        ),
    ]
