# Generated by Django 4.0 on 2022-10-21 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_alter_booklist_title_alter_list_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='spoiler',
            field=models.BooleanField(choices=[(False, 'No'), (True, 'Yes')], default=False, null=True),
        ),
    ]
