# Generated by Django 4.0 on 2022-10-25 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('app', '0034_alter_rating_list_alter_rating_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='list',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.list'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
        ),
    ]
