# Generated by Django 4.0 on 2022-10-25 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_alter_rating_list_alter_rating_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='list',
        ),
    ]
