# Generated by Django 4.0 on 2022-10-25 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_remove_rating_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='musicrating',
            name='list',
        ),
        migrations.RemoveField(
            model_name='musicrating',
            name='user',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='user',
        ),
        migrations.DeleteModel(
            name='BookRating',
        ),
        migrations.DeleteModel(
            name='MusicRating',
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
