# Generated by Django 4.0 on 2022-10-25 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0040_remove_review_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookreview',
            name='rate',
        ),
        migrations.RemoveField(
            model_name='musicreview',
            name='rate',
        ),
    ]
