# Generated by Django 4.0 on 2023-01-03 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0043_alter_feedback_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='location',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='profile_pic',
        ),
    ]
