# Generated by Django 4.0 on 2023-01-05 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0045_alter_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booklist',
            name='genre',
            field=models.ManyToManyField(blank=True, to='app.BookGenre'),
        ),
        migrations.AlterField(
            model_name='list',
            name='genre',
            field=models.ManyToManyField(blank=True, to='app.Genre'),
        ),
        migrations.AlterField(
            model_name='musiclist',
            name='genre',
            field=models.ManyToManyField(blank=True, to='app.MusicGenre'),
        ),
    ]
